const URL='https://wpjixgfnynrboptwpotd.supabase.co';
const KEY='sb_publishable_IwnnE09a7GnBzIHG-Z4ssQ_gTJTqLfg';
const stageDb={Sourcing:'sourcing','CV Review':'cv_review','HR Call':'hr_call','HR Interview':'hr_interview','Technical Interview':'technical_interview',Offer:'offer',Hired:'hired',Rejected:'rejected','On Hold':'on_hold','Talent Pool':'talent_pool'};
function extractContact(text=''){const n=text.replace(/[\u200c\u200f\u202a-\u202e]/g,' ');const email=(n.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)||[])[0]||'';const phones=n.match(/(?:\+?98|0098|0)?[\s\-()]?9\d{2}[\s\-()]?\d{3}[\s\-()]?\d{4}/g)||[];let phone=(phones[0]||'').replace(/[^\d+]/g,'');if(phone.startsWith('0098'))phone='+98'+phone.slice(4);else if(phone.startsWith('98')&&!phone.startsWith('+'))phone='+'+phone;else if(/^9\d{9}$/.test(phone))phone='0'+phone;return{email,phone}}
async function refresh(rt){if(!rt)return null;const r=await fetch(`${URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:rt})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.msg||d?.error_description||d?.message||'Session expired');return d}
function expired(token){try{const p=JSON.parse(Buffer.from((token||'').split('.')[1]||'','base64url').toString());return !p.exp||p.exp*1000<Date.now()+15000}catch{return true}}
async function raw(path,{method='GET',token,body,prefer}={}){const r=await fetch(`${URL}/rest/v1/${path}`,{method,headers:{apikey:KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(prefer?{Prefer:prefer}:{})},body:body?JSON.stringify(body):undefined});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}return{r,data:d}}
async function ensureFresh(c){if((!c.token||expired(c.token))&&c.refreshToken){const f=await refresh(c.refreshToken);c.token=f.access_token;c.refreshToken=f.refresh_token||c.refreshToken;c.user=f.user||c.user;c.refreshed={access_token:c.token,refresh_token:c.refreshToken,user:c.user}}}
async function sb(path,opts,c){await ensureFresh(c);let o=await raw(path,{...opts,token:c.token});if(o.r.status===401&&c.refreshToken){const f=await refresh(c.refreshToken);c.token=f.access_token;c.refreshToken=f.refresh_token||c.refreshToken;c.user=f.user||c.user;c.refreshed={access_token:c.token,refresh_token:c.refreshToken,user:c.user};o=await raw(path,{...opts,token:c.token})}if(!o.r.ok)throw new Error(o.data?.message||o.data?.hint||o.data?.details||o.data?.error||`Database error ${o.r.status}`);return o.data}
async function activity(c,orgId,candidateId,userId,action,text,metadata={}){return sb('activities',{method:'POST',body:{organization_id:orgId,candidate_id:candidateId,actor_id:userId,action,metadata:{text,...metadata}}},c)}
function needOrg(req){const id=req.body?.orgId;if(!id)throw new Error('Company is required');return id}
async function roleFor(c,orgId,userId){const r=await sb(`organization_members?organization_id=eq.${encodeURIComponent(orgId)}&user_id=eq.${encodeURIComponent(userId)}&is_active=eq.true&select=role`,{},c);return r?.[0]?.role||null}
async function requireRole(c,orgId,userId,allowed){const role=await roleFor(c,orgId,userId);if(!role||!allowed.includes(role)){const e=new Error('You do not have permission for this action');e.status=403;throw e}return role}
export default async function handler(req,res){const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const refreshToken=req.headers['x-refresh-token']||req.body?.refreshToken||'';if(!token&&!refreshToken)return res.status(401).json({error:'Missing session token',code:'AUTH_REQUIRED'});const c={token,refreshToken,user:null,refreshed:null};const{op}=req.body||{};try{await ensureFresh(c);const userId=req.body.userId;let result;
if(op==='bootstrap'){const[organizations,memberships]=await Promise.all([sb('organizations?select=*&order=created_at.asc',{},c),sb(`organization_members?select=organization_id,role,is_active&user_id=eq.${encodeURIComponent(userId)}&order=created_at.asc`,{},c)]);result={organizations,memberships}}
else if(op==='load'){const orgId=needOrg(req);await requireRole(c,orgId,userId,['hr_admin','hr','hiring_manager','interviewer','viewer']);const q=`organization_id=eq.${encodeURIComponent(orgId)}`;const[requests,jobs,candidates,activities,comments,communications,evaluations,templates]=await Promise.all([sb(`hiring_requests?select=*&${q}&order=created_at.desc`,{},c),sb(`jobs?select=*&${q}&order=created_at.desc`,{},c),sb(`candidates?select=*&${q}&order=created_at.desc`,{},c),sb(`activities?select=*&${q}&order=created_at.desc`,{},c),sb(`candidate_comments?select=*&${q}&order=created_at.desc`,{},c),sb(`candidate_communications?select=*&${q}&order=created_at.desc`,{},c),sb(`interview_evaluations?select=*&${q}&order=created_at.desc`,{},c),sb(`message_templates?select=*&${q}&order=template_key.asc`,{},c)]);result={requests,jobs,candidates,activities,comments,communications,evaluations,templates}}
else if(op==='create_organization'){const name=(req.body.name||'').trim();if(!name)throw new Error('Company name is required');result={organization_id:await sb('rpc/create_organization',{method:'POST',body:{org_name:name}},c)}}
else if(op==='rename_organization'){const orgId=needOrg(req);await requireRole(c,orgId,userId,['hr_admin']);const name=(req.body.name||'').trim();const rows=await sb(`organizations?id=eq.${encodeURIComponent(orgId)}`,{method:'PATCH',prefer:'return=representation',body:{name}},c);result={organization:rows?.[0]}}
else if(op==='list_members'){const orgId=needOrg(req);await requireRole(c,orgId,userId,['hr_admin']);result={members:await sb('rpc/org_member_directory',{method:'POST',body:{org:orgId}},c)}}
else if(op==='add_member'){const orgId=needOrg(req);await requireRole(c,orgId,userId,['hr_admin']);result={user_id:await sb('rpc/admin_add_member_by_email',{method:'POST',body:{org:orgId,member_email:(req.body.email||'').trim(),member_role:req.body.role||'viewer'}},c)}}
else if(op==='update_member'){const orgId=needOrg(req);await requireRole(c,orgId,userId,['hr_admin']);await sb('rpc/admin_update_member',{method:'POST',body:{org:orgId,member_user:req.body.memberUser,member_role:req.body.role,member_active:!!req.body.isActive}},c);result={ok:true}}
else if(op==='create_request'){const orgId=needOrg(req);await requireRole(c,orgId,userId,['hr_admin','hr','hiring_manager']);const f=req.body.form||{};const rows=await sb('hiring_requests',{method:'POST',prefer:'return=representation',body:{organization_id:orgId,created_by:userId,title:f.title,department:f.department,hiring_manager_name:f.manager||null,openings:Number(f.hc)||1,reason:'Growth / Replacement',business_justification:'Submitted via Recruitment OS',job_description:f.jd,responsibilities:f.jd,must_have:f.must||f.jd,seniority:'Not specified'}},c);result={request:rows?.[0]}}
else if(op==='approve_request'){const orgId=needOrg(req);await requireRole(c,orgId,userId,['hr_admin','hr']);const rows=await sb(`hiring_requests?id=eq.${encodeURIComponent(req.body.id)}&organization_id=eq.${encodeURIComponent(orgId)}`,{method:'PATCH',prefer:'return=representation',body:{status:'approved',approved_by:userId,approved_at:new Date().toISOString()}},c);const r=rows?.[0];if(!r)throw new Error('Request not found');const js=await sb('jobs',{method:'POST',prefer:'return=representation',body:{organization_id:orgId,hiring_request_id:r.id,title:r.title,department:r.department,hiring_manager_name:r.hiring_manager_name,openings:r.openings,employment_type:r.employment_type,work_model:r.work_model,priority:r.priority,target_hiring_date:r.target_hiring_date,job_description:r.job_description,responsibilities:r.responsibilities,must_have:r.must_have,nice_to_have:r.nice_to_have,seniority:r.seniority,minimum_experience:r.minimum_experience,education_requirement:r.education_requirement,salary_from:r.salary_from,salary_to:r.salary_to,status:'open'}},c);result={request:r,job:js?.[0]}}
else if(op==='reject_request'){const orgId=needOrg(req);await requireRole(c,orgId,userId,['hr_admin','hr']);const rows=await sb(`hiring_requests?id=eq.${encodeURIComponent(req.body.id)}&organization_id=eq.${encodeURIComponent(orgId)}`,{method:'PATCH',prefer:'return=representation',body:{status:'rejected',approved_by:userId,approved_at:new Date().toISOString()}},c);result={request:rows?.[0]}}
else if(op==='create_candidate'){const orgId=needOrg(req);await requireRole(c,orgId,userId,['hr_admin','hr']);const x=req.body.candidate||{},auto=extractContact(x.resumeText||'');const rows=await sb('candidates',{method:'POST',prefer:'return=representation',body:{organization_id:orgId,job_id:req.body.jobId,full_name:x.name,email:x.email||auto.email||null,phone:x.phone||auto.phone||null,stage:'cv_review',hr_approval:'pending',resume_text:x.resumeText||null,resume_file_name:x.fileName||null,screening_score:x.score,screening_summary:x.why,created_by:userId}},c);const row=rows?.[0];if(row)await Promise.all([activity(c,orgId,row.id,userId,'resume_screened',`Resume uploaded and screened — score ${x.score}`),activity(c,orgId,row.id,userId,'stage_changed','Added to CV Review',{to:'cv_review'})]);result={candidate:row}}
else if(op==='move_candidate'){const orgId=needOrg(req);await requireRole(c,orgId,userId,['hr_admin','hr']);const stage=stageDb[req.body.stage]||req.body.stage;const rows=await sb(`candidates?id=eq.${encodeURIComponent(req.body.candidateId)}&organization_id=eq.${encodeURIComponent(orgId)}`,{method:'PATCH',prefer:'return=representation',body:{stage}},c);await activity(c,orgId,req.body.candidateId,userId,'stage_changed',`Stage changed to ${req.body.stage}`,{to:stage});result={candidate:rows?.[0]}}
else if(op==='reject_candidate'){const orgId=needOrg(req);await requireRole(c,orgId,userId,['hr_admin','hr']);const cid=req.body.candidateId,fromStage=req.body.fromStage||'',reason=(req.body.reason||'').trim();const rows=await sb(`candidates?id=eq.${encodeURIComponent(cid)}&organization_id=eq.${encodeURIComponent(orgId)}`,{method:'PATCH',prefer:'return=representation',body:{stage:'rejected',hr_approval:'rejected'}},c);await activity(c,orgId,cid,userId,'candidate_rejected',`Rejected from ${fromStage}${reason?` — ${reason}`:''}`,{from_stage:fromStage,reason});result={candidate:rows?.[0]}}
else if(op==='search_candidates'){const orgId=needOrg(req);await requireRole(c,orgId,userId,['hr_admin','hr','hiring_manager','interviewer','viewer']);const q=(req.body.query||'').trim();if(!q)result={results:[]};else{const safe=q.replace(/[%*,()]/g,'');const cs=await sb(`candidates?organization_id=eq.${encodeURIComponent(orgId)}&or=(full_name.ilike.*${encodeURIComponent(safe)}*,email.ilike.*${encodeURIComponent(safe)}*,phone.ilike.*${encodeURIComponent(safe)}*)&select=id,job_id,full_name,email,phone,stage,screening_score&limit=50`,{},c);const ids=[...new Set((cs||[]).map(x=>x.job_id).filter(Boolean))];let js=[];if(ids.length)js=await sb(`jobs?organization_id=eq.${encodeURIComponent(orgId)}&id=in.(${ids.join(',')})&select=id,title`,{},c);const jm=Object.fromEntries(js.map(j=>[j.id,j.title]));result={results:(cs||[]).map(x=>({...x,job_title:jm[x.job_id]||'Unknown Job'}))}}}
else if(op==='hr_decision'){const orgId=needOrg(req);await requireRole(c,orgId,userId,['hr_admin','hr']);const approved=!!req.body.approved,stage=approved?'hr_call':'rejected',approval=approved?'approved':'rejected';const rows=await sb(`candidates?id=eq.${encodeURIComponent(req.body.candidateId)}&organization_id=eq.${encodeURIComponent(orgId)}`,{method:'PATCH',prefer:'return=representation',body:{stage,hr_approval:approval}},c);await activity(c,orgId,req.body.candidateId,userId,'hr_decision',approved?'HR approved candidate → HR Call':'HR rejected candidate',{approved});result={candidate:rows?.[0]}}
else if(op==='save_evaluation'){const orgId=needOrg(req);await requireRole(c,orgId,userId,['hr_admin','hr','hiring_manager','interviewer']);const e=req.body.evaluation||{};const body={organization_id:orgId,candidate_id:req.body.candidateId,interview_type:e.interview_type,interviewer_id:userId,communication_score:e.communication_score||null,culture_fit_score:e.culture_fit_score||null,motivation_score:e.motivation_score||null,career_fit_score:e.career_fit_score||null,technical_knowledge_score:e.technical_knowledge_score||null,problem_solving_score:e.problem_solving_score||null,experience_score:e.experience_score||null,role_fit_score:e.role_fit_score||null,overall_score:Number(e.overall_score),strengths:e.strengths||null,concerns:e.concerns||null,notes:e.notes||null,recommendation:e.recommendation,updated_at:new Date().toISOString()};const rows=await sb('interview_evaluations?on_conflict=candidate_id,interviewer_id,interview_type',{method:'POST',prefer:'resolution=merge-duplicates,return=representation',body},c);await activity(c,orgId,req.body.candidateId,userId,'interview_evaluation',`${e.interview_type==='hr'?'HR':'Technical'} interview evaluation saved`,{interview_type:e.interview_type,recommendation:e.recommendation,overall_score:Number(e.overall_score)});result={evaluation:rows?.[0]}}
else if(op==='save_template'){const orgId=needOrg(req);await requireRole(c,orgId,userId,['hr_admin','hr']);const t=req.body.template||{};const body={organization_id:orgId,template_key:t.template_key,channel:t.channel,subject:t.subject||null,body:t.body||'',is_active:t.is_active!==false,created_by:userId,updated_at:new Date().toISOString()};const rows=await sb('message_templates?on_conflict=organization_id,template_key,channel',{method:'POST',prefer:'resolution=merge-duplicates,return=representation',body},c);result={template:rows?.[0]}}
else if(op==='add_comment'){const orgId=needOrg(req);await requireRole(c,orgId,userId,['hr_admin','hr','hiring_manager','interviewer']);const rows=await sb('candidate_comments',{method:'POST',prefer:'return=representation',body:{organization_id:orgId,candidate_id:req.body.candidateId,author_id:userId,body:req.body.body}},c);await activity(c,orgId,req.body.candidateId,userId,'comment_added','New team comment added');result={comment:rows?.[0]}}
else if(op==='create_communication'){const orgId=needOrg(req);await requireRole(c,orgId,userId,['hr_admin','hr']);const x=req.body.communication||{},logged=['call','feedback'].includes(x.channel);const rows=await sb('candidate_communications',{method:'POST',prefer:'return=representation',body:{organization_id:orgId,candidate_id:req.body.candidateId,channel:x.channel,status:logged?'logged':'draft',recipient:x.recipient||null,subject:x.subject||null,body:x.body||null,metadata:x.metadata||{},created_by:userId}},c);const row=rows?.[0];await activity(c,orgId,req.body.candidateId,userId,'communication_created',`${x.channel.toUpperCase()} ${logged?'logged':'draft created'}`);result={communication:row}}
else if(op==='approve_communication'){const orgId=needOrg(req);await requireRole(c,orgId,userId,['hr_admin','hr']);const ex=await sb(`candidate_communications?id=eq.${encodeURIComponent(req.body.id)}&organization_id=eq.${encodeURIComponent(orgId)}&select=*`,{},c),item=ex?.[0];if(!item)throw new Error('Communication not found');const rows=await sb(`candidate_communications?id=eq.${encodeURIComponent(req.body.id)}`,{method:'PATCH',prefer:'return=representation',body:{status:'queued',approved_by:userId,approved_at:new Date().toISOString()}},c);result={communication:rows?.[0],provider_connected:false}}
else return res.status(400).json({error:'Unknown operation'});
return res.json({...result,...(c.refreshed?{session:c.refreshed}:{})})}catch(e){const m=e.message||'Database operation failed';const auth=/jwt|session|token|expired|refresh/i.test(m);return res.status(e.status||(auth?401:500)).json({error:m,code:auth?'SESSION_EXPIRED':e.status===403?'FORBIDDEN':'DATA_ERROR'})}}
